### PR TITLE
Adding submit github action

### PR DESCRIPTION
**Pull request by louisgv**
Hi @kawamataryo,

Thanks for making chikamichi - your extension is awesome! 

I was looking for some way to contribute, and thought that maybe an automated submission pipeline for the zip archive could be helpful. I created a github action called [bpp](https://github.com/marketplace/actions/browser-plugin-publisher) that can submit the zip to the Chrome/Firefox stores automatically for you. It is set to run manually from the github action tab, but we can tweak it to run as frequent as you wish! The only thing you would need to create is a `SUBMIT_KEYS` github repository secret.

This secret is a json, with the schema defined [here](https://github.com/plasmo-corp/bpp/blob/main/keys.schema.json).

Here's a sample key:

```json
{
  "$schema": "https://raw.githubusercontent.com/plasmo-corp/bpp/main/keys.schema.json",
  "chrome": {
    "zip": "./extension.crx",
    "clientId": "123",
    "refreshToken": "789",
    "extId": "abcd"
  },
  "firefox": {
    "zip": "./extension.xpi",
    "extId": "123",
    "sessionid": "abcd"
  }
}

```

You can find instructions on how to get those keys in the schema, or if you use vscode, the schema should provide hint/intelisense when hovering over the json properties. If you need any help in setting up the keys, feel free to @ me! Otherwise if this doesn't seem necessary, feel free to close the PR :)

### CODE REVIEW

**Comment by kawamataryo** [comment]
Awesome! This is a very good contribution!
Thanks a lot :)

Please wait a moment while I set SUBMIT_KEYS to secret.

**Comment by kawamataryo** [comment]
@louisgv 

Sorry for the delay in response.

I'm setting this up now, but I couldn't find a way to get the clientSecret on this page.

https://github.com/fregante/chrome-webstore-upload/blob/main/How%20to%20generate%20Google%20API%20keys.md

It says it is not used in v0.5 or later, so should I just put in an empty string?

**Comment by louisgv** [comment]
@kawamataryo 
Oopsie, my bad! I just fixed the schema and publish a new version so now the client_secret is an optional parameter for google store v1 API. Can you please reload your vscode and see if the schema stop complaining about the missing keys?

**Comment by kawamataryo** [comment]
@louisgv 

I tried to release it using these GitHub Acitions, but the following error occurred.
Do you have any idea what it is?

image

For your reference, here is the content of SUMIT_KEYS that I set.

```
{
  "$schema": "https://raw.githubusercontent.com/plasmo-corp/bpp/main/keys.schema.json",
  "chrome": {
    "zip": "./extension.crx",
    "clientId": "CLIENT_ID",
    "refreshToken": "TOKEN",
    "extId": "gkhobepjbiepngbeikhbpnfgjcjgmgha"
  },
  "firefox": {
    "zip": "./extension.xpi",
    "extId": "chikamichi",
    "sessionid": "SETTION_ID"
  }
}
```

**Comment by louisgv** [comment]
@kawamataryo I'm investigating now - it seems chromium is not included in the github action runtime which was an oversight I made when testing this action on my end. I will get back to you with a fix soon! And yes, that sessionid should be what you need (it's what https://github.com/avi12/web-ext-deploy tool extracted: https://github.com/avi12/web-ext-deploy/blob/20609103197c08f9e95207ad22a9c45811c91aab/src/get-sign-in-cookie.ts#L70-L75)

**Comment by louisgv** [comment]
@kawamataryo tracking this issue here: https://github.com/plasmo-corp/bpp/issues/13

I'm working on a patch now to revamp the whole firefox submission flow. Will land it hopefully by end of today. The firefox key will be updated from the sessionid cookie into apiKey and apiSecret as described in web-ext doc: https://addons.mozilla.org/en-US/developers/addon/api/key/

I will also bump the bpp github-action version to v2 once the migration work is done. Apologize for the inconvenience!

**Comment by kawamataryo** [comment]
@louisgv 

Thank you for your research and response :)
I am looking forward to the release of v2.

**Comment by louisgv** [comment]
@kawamataryo The new version has been deployed, I'm testing it locally now, but the new key schema should be ready for you to fix the secret. I pushed it to the same `v1` instead of moving to `v2` since the previous method was not working anyway. So all you will have to change is the secret for firefox (using apiKey and apiSecret as mentioned above and in the schema)

Also, you might want to swap the schema to v1 instead of main:

```
  "$schema": "https://raw.githubusercontent.com/plasmo-corp/bpp/v1/keys.schema.json",
```

Will do more testing on my own extension and hopefully we caught more bug! Thanks so much for being a pioneer :D

**Comment by kawamataryo** [comment]
@louisgv 

Thanks for the fix.
I will fix the secret and try it in the next release :)

**Pull request merged**
